version: "3.4"

services:
  #main www
  glpi:
    image: glpi:9.4.2
    ports:
      - 80:80
    volumes:
      - ./config_db.php:/var/www/html/config/config_db.php
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMEZONE=Europe/Paris
  # execute cron tasks
  glpi_cron:
    image: glpi:9.4.2
    volumes:
      - ./config_db.php:/var/www/html/config/config_db.php
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMEZONE=Europe/Paris
    restart: always
    entrypoint: "php /var/www/html/front/cron.php && sleep 30"
  # db
  mysql:
    image: mariadb:10
    volumes:
      - database:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretrootpassword
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=mysecretglpipassword
      - TZ=Europe/Paris
	  
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /local/mysql/storage/placement